server {
    listen 18080;
    listen [::]:18080;
    server_name _;

    location /stream {
        proxy_pass https://127.0.0.1:60002;
        proxy_ssl_verify off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_read_timeout 300s;
    }
}

